# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03d_utils.config.ipynb.

# %% auto #0
__all__ = ['set_config', 'get_config', 'config']

# %% ../../nbs/03d_utils.config.ipynb #ee11b1c3
from copy import copy
from types import SimpleNamespace
from typing import Callable, Union, Optional, TypeVar
from contextlib import contextmanager

import numpy as np
import warnings

# %% ../../nbs/03d_utils.config.ipynb #97bcda6a
class Config(SimpleNamespace):
    "Config"
    precision: int
    threshold_max: int
    threshold_min: int
    sci_mode: Optional[bool]
    show_mem_above: int
    indent: int
    color: bool
    verbose: bool
    deeper_width: int
    plt_seed: int
    fig_close: bool
    fig_show: bool
    show_histogram: bool

    def __init__(self,
            precision     :int            = 3,    # Digits after `.`
            threshold_max :int            = 3,    # .abs() larger than 1e3 -> Sci mode
            threshold_min :int            = -4,   # .abs() smaller that 1e-4 -> Sci mode
            sci_mode      :Optional[bool] = None, # Sci mode (2.3e4). None=auto
            show_mem_above:int            = 1024, # Show memory usage in b/Kb/Mb/Gb if it's larger than this
            indent        :int            = 2,    # Indent for .deeper()
            color         :bool           = True, # ANSI colors in text
            verbose       :bool           = False,# Show the default repr by default
            deeper_width  :int            = 9,    # For .deeper, width per level
            plt_seed      :int            = 42,   # Sampling seed for `plot`
            fig_close     :bool           = True, # Close matplotlib Figure
            fig_show      :bool           = False,# Call `plt.show()` for `.plt`, `.chans` and `.rgb`
            show_histogram:bool           = True  # Show the histogram in lovely(): '▁▂▃▃▆█▆▃▁▁'
    ) -> None:
        super().__init__(**{k:v for k,v in locals().items() if k not in ["self", "__class__"]})

_defaults: Config = Config()
_config: Config = copy(_defaults)

# %% ../../nbs/03d_utils.config.ipynb #bdb06b31
# Allows passing None as an argument to reset the
class _Default():
    def __repr__(self):
        return "Ignore"
D = _Default()
Default = TypeVar("Default")

# %% ../../nbs/03d_utils.config.ipynb #9178a800
def set_config( precision       :Optional[Union[Default,int]]     =D,
                threshold_min   :Optional[Union[Default,int]]     =D,
                threshold_max   :Optional[Union[Default,int]]     =D,
                sci_mode        :Optional[Union[Default,bool]]    =D,
                show_mem_above  :Optional[Union[Default,bool]]    =D,
                indent          :Optional[Union[Default,bool]]    =D,
                color           :Optional[Union[Default,bool]]    =D,
                verbose         :Optional[Union[Default,bool]]    =D,
                deeper_width    :Optional[Union[Default,int]]     =D,
                repr            :Optional[Union[Default,Callable]]=D,
                str             :Optional[Union[Default,Callable]]=D,
                plt_seed        :Optional[Union[Default,int]]     =D,
                fig_close       :Optional[Union[Default,bool]]    =D,
                fig_show        :Optional[Union[Default,bool]]    =D,
                show_histogram  :Optional[Union[Default,bool]]    =D,
                ) -> None:

    "Set config variables"
    args = locals().copy()
    for k,v in args.items():
        if v != D:

            if k in ["repr", "str"]:
                warnings.warn("The use of 'repr' and 'str' as configuration options is deprecated, because Numpy 2.0 makes it hard to set them.", DeprecationWarning)
                continue

            if v is None:
                setattr(_config, k, getattr(_defaults, k))
            else:
                setattr(_config, k, v)

# %% ../../nbs/03d_utils.config.ipynb #f38bfe47
def get_config() -> Config:
    "Get a copy of config variables"
    return copy(_config)

# %% ../../nbs/03d_utils.config.ipynb #1d87b1f7
@contextmanager
def config( precision       :Optional[Union[Default,int]]     =D,
            threshold_min   :Optional[Union[Default,int]]     =D,
            threshold_max   :Optional[Union[Default,int]]     =D,
            sci_mode        :Optional[Union[Default,bool]]    =D,
            show_mem_above  :Optional[Union[Default,bool]]    =D,
            indent          :Optional[Union[Default,bool]]    =D,
            color           :Optional[Union[Default,bool]]    =D,
            verbose         :Optional[Union[Default,bool]]    =D,
            deeper_width    :Optional[Union[Default,int]]     =D,
            repr            :Optional[Union[Default,Callable]]=D,
            str             :Optional[Union[Default,Callable]]=D,
            plt_seed        :Optional[Union[Default,int]]     =D,
            fig_close       :Optional[Union[Default,bool]]    =D,
            fig_show        :Optional[Union[Default,bool]]    =D,
            show_histogram  :Optional[Union[Default,bool]]    =D
            ):
    "Context manager for temporarily setting config options"
    new_opts = { k:v for k, v in locals().items() if v != D}
    old_opts = copy(get_config().__dict__)

    try:
        set_config(**new_opts)
        yield
    finally:
        set_config(**old_opts)
