# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03_utils.utils.ipynb.

# %% auto #0
__all__ = ['InputType', 'sci_mode', 'pretty_str', 'sparse_join', 'ansi_color', 'bytes_to_human', 'unicode_miniplot',
           'np_to_str_common', 'history_warning', 'in_debugger', 'svg_miniplot']

# %% ../../nbs/03_utils.utils.ipynb #0b0580b8
import sys
from collections import defaultdict
import warnings
import numpy as np
from typing import Optional, Union
from .config import get_config
from functools import cached_property

# %% ../../nbs/03_utils.utils.ipynb #c5916579
InputType = Union[np.ndarray, np.number, float]

# %% ../../nbs/03_utils.utils.ipynb #abc540e5
def sample( x       :np.ndarray,
            max_s   :int,
            plt0    :bool):

    # Samples up to max_s elements and returns
    #   - samples from x
    #   - original x min (None = no good numbes in x)
    #   - original x max (None = no good numbes in x)

    # Ignore NaN and Inf.
    x = x[ np.isfinite(x) ]
    x_min = x_max = None

    if x.size:
        x_min, x_max = x.min(), x.max()

        # An option to ignore zeros
        if not plt0: x = x[x != 0.]

        if x.size > max_s and max_s > 0:
            rng = np.random.default_rng( get_config().plt_seed )
            x = rng.choice(x.reshape(-1), max_s) # Sample with replacement for efficiency

    return (x, x_min, x_max)

# %% ../../nbs/03_utils.utils.ipynb #356f1db2
# Do we want this float in decimal or scientific mode?
def sci_mode(f: float):
    config = get_config()
    return ((abs(f) < 10**config.threshold_min) or
            (abs(f) > 10**config.threshold_max))

# %% ../../nbs/03_utils.utils.ipynb #9cc727ea
# Convert an ndarray or scalar into a string.
# This only looks good for small arrays, which is how it's intended to be used.
def pretty_str(x):
    """A slightly better way to print `float`-y values.
    Works for `np.ndarray`, `torch.Tensor`, `jax.DeviceArray`, and scalars."""

    if isinstance(x, int):
        return '{}'.format(x)
    elif isinstance(x, float):
        if x == 0.:
            return "0."

        sci = sci_mode(x) if get_config().sci_mode is None else get_config().sci_mode

        fmt = f"{{:.{get_config().precision}{'e' if sci else 'f'}}}"

        return fmt.format(x)
    elif x.ndim == 0:
            return pretty_str(x.item())
    else:
        slices = [pretty_str(x[i]) for i in range(0, x.shape[0])]
        return '[' + ", ".join(slices) + ']'

# %% ../../nbs/03_utils.utils.ipynb #13f0ea89
def sparse_join(lst, sep=" "):
    # Join non-empty list elements into a space-sepaeated string
    return sep.join( [ l for l in lst if l] )

# %% ../../nbs/03_utils.utils.ipynb #f60c399e
def ansi_color(s: str, col: str, use_color=True):
        "Very minimal ANSI color support"
        style = defaultdict(str)
        style["grey"] = "\x1b[38;2;127;127;127m"
        style["red"] = "\x1b[31m"
        style["green"] = "\x1b[32m"
        style["blue"] = "\x1b[34m"
        style["yellow"] = "\x1b[33m"
        end_style = "\x1b[0m"

        return style[col]+s+end_style if use_color else s

# %% ../../nbs/03_utils.utils.ipynb #05c08059
def bytes_to_human(num_bytes):
    units = ['B', 'KiB', 'MiB', 'GiB']

    value = num_bytes
    for unit in units:
        if value < 1024.0 / 10:
            break
        value /= 1024.0

    if value % 1 == 0 or value >= 10:
        return f"{round(value)} {unit}" # type: ignore
    else:
        return f"{value:.1f} {unit}" # type: ignore

# %% ../../nbs/03_utils.utils.ipynb #0148b2d2
def unicode_miniplot(counts: np.ndarray, blocks=" ▁▂▃▄▅▆▇█"):
    counts = np.asarray(counts)
    if counts.size == 0:
        return ""

    peak = np.max(counts)
    if peak <= 0:
        return blocks[0] * len(counts)

    levels = len(blocks) - 1
    return ''.join(
        blocks[min(levels, int(np.ceil(v / peak * levels)))] if v > 0 else blocks[0]
        for v in counts
    )


# %% ../../nbs/03_utils.utils.ipynb #08a09312
def np_to_str_common(   x: Union[np.ndarray, np.number],       # Input
                        color: bool=True,   # ANSI color highlighting
                        ddof=0,             # For "std" unbiasing
                        show_histogram: bool=False # Show the histogram
                        ):                       
    if x.size == 0:
        return ansi_color("empty", "grey", color)

    zeros = ansi_color("all_zeros", "grey", color) if np.equal(x, 0.).all() and x.size > 1 else None
    pinf = ansi_color("+Inf!", "red", color) if np.isposinf(x).any() else None # type: ignore
    ninf = ansi_color("-Inf!", "red", color) if np.isneginf(x).any() else None # type: ignore
    nan = ansi_color("NaN!", "red", color) if np.isnan(x).any() else None

    attention = sparse_join([zeros,pinf,ninf,nan])

    summary=None
    if not zeros and isinstance(x, np.ndarray):
        # Calculate stats on good values only.
        gx = x[ np.isfinite(x) ]

        if gx.size >= 2:
            _min, _max = gx.min(), gx.max()
            if show_histogram and _min != _max and gx.size > 50:
                counts, _ = np.histogram(sample(gx, 10000, True)[0], bins=10, range=(_min, _max))
                minmax = f"x∈[{pretty_str(_min)} |{unicode_miniplot(counts)}| {pretty_str(_max)}]" if gx.size > 2 else None
            else:
                minmax = f"x∈[{pretty_str(_min)}, {pretty_str(_max)}]" if gx.size > 2 else None
        else: minmax = None

        meanstd = f"μ={pretty_str(gx.mean())} σ={pretty_str(gx.std(ddof=ddof))}" if gx.size >= 2 else None
        summary = sparse_join([minmax, meanstd])

    return sparse_join([ summary, attention])

# %% ../../nbs/03_utils.utils.ipynb #b3316ced
def history_warning():
    "Issue a warning (once) ifw e are running in IPYthon with output cache enabled"
    if "get_ipython" in globals() and (ipython := get_ipython()) and ipython.cache_size > 0: # type: ignore
        warnings.warn("IPYthon has its output cache enabled. See https://xl0.github.io/lovely-tensors/history.html")

# %% ../../nbs/03_utils.utils.ipynb #3f9eee06
def in_debugger():
    """Returns True if a debugger was used.

    Note: This funciton will keep returning True even after you exit the debugger."""
    return getattr(sys, "gettrace", None) and sys.gettrace() is not None

# %% ../../nbs/03_utils.utils.ipynb #29dc103a
def svg_miniplot(counts: np.ndarray, width=60, height=18):
    counts = np.asarray(counts)
    if counts.size == 0:
        return ""

    step = width / len(counts)
    bar_w = max(step - 1.5, 1)
    rects = []

    scale = max(abs(v) for v in counts) or 1
    baseline_y = height - 1
    baseline = f"<line x1='0' y1='{baseline_y:.2f}' x2='{width}' y2='{baseline_y:.2f}' stroke='#c5ced8' stroke-width='1' />"
    for i, v in enumerate(counts):
        if v == 0:
            continue
        h = abs(v) / scale * (height - 2)
        y = height - 1 - h
        fill = '#2f6fed'
        rects.append(f"<rect x='{i * step:.2f}' y='{y:.2f}' width='{bar_w:.2f}' height='{max(h, 1):.2f}' rx='0.8' fill='{fill}' />")

    return (
        f"<svg width='{width}' height='{height}' viewBox='0 0 {width} {height}' xmlns='http://www.w3.org/2000/svg'  style='background:transparent'>"
        + '\n  '.join(("", baseline,  *rects))
        + "\n</svg>"
    )

