# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/lovely-numpy',
                'doc_host': 'https://xl0.github.io',
                'git_url': 'https://github.com/xl0/lovely-numpy',
                'lib_path': 'lovely_numpy'},
  'syms': {'lovely_numpy.core': {'lovely_numpy.core.foo': ('core.html#foo', 'lovely_numpy/core.py')}}}
