# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_patch.ipynb.

# %% auto 0
__all__ = ['monkey_patch']

# %% ../nbs/10_patch.ipynb 3
import numpy as np
from .repr_str import StrProxy

# %% ../nbs/10_patch.ipynb 4
def monkey_patch():
    "Monkey-patch lovely features into `numpy.ndarray`" 

    def _repr(self: np.ndarray):
        return str(StrProxy(self))

    np.set_string_function(_repr, False)
    np.set_string_function(_repr, True)
